import Head from 'next/head'
import clientPromise from '../../lib/mongodb'
import { useEffect } from 'react'
import styles from '../../styles/Home.module.css'
import { ObjectId } from 'mongodb'


export async function getServerSideProps(context) {
  try {
    await clientPromise
   
    const client = await clientPromise
    const db = client.db("TheOnlineMenu")

    const restaurant = await db
            .collection("Restaurants")
            .findOne({_id:ObjectId('64114efc34c6df91e004a8d3')})
    return {
      props: { restaurant: JSON.stringify(restaurant) },
    }
  } catch (e) {
    console.error(e)
    return {
      props: { isConnected: false },
    }
  }
}


export default function Restaurant({restaurant}){

  useEffect(()=>{
    console.log(JSON.parse(restaurant))
  },[])
 
   return (
     <>
       <Head>
         <title>Create Next App</title>
         <meta name="description" content="Generated by create next app" />
         <meta name="viewport" content="width=device-width, initial-scale=1" />
         <link rel="icon" href="/favicon.ico" />
       </Head>
       <main className={styles.main}>
        <h1>Restaurant name</h1>
       </main>
     </>
   )

}
