import Head from 'next/head'
import clientPromise from '../lib/mongodb'
import { useEffect } from 'react'
import styles from '../styles/Home.module.css'
import Link from 'next/link';


export async function getServerSideProps(context) {
  try {
    await clientPromise
   
    const client = await clientPromise
    const db = client.db("TheOnlineMenu")

    const restaurants = await db
            .collection("Restaurants")
            .find({})
            .sort({ })
            .limit(20)
            .toArray();
    return {
      props: { restaurants: JSON.stringify(restaurants) },
    }
  } catch (e) {
    console.error(e)
    return {
      props: { isConnected: false },
    }
  }
}


export default function Home({restaurants}){

  useEffect(()=>{
    console.log(JSON.parse(restaurants))
  },[])
 
   return (
     <>
       <Head>
         <title>Create Next App</title>
         <meta name="description" content="Generated by create next app" />
         <meta name="viewport" content="width=device-width, initial-scale=1" />
         <link rel="icon" href="/favicon.ico" />
       </Head>
       <main className={styles.main}>
        <h1>Hello</h1>
        <Link
              href={{
                pathname: '/restaurant-creator'
              }}
            >
              <button>Create Restaurant</button>
            </Link>
       </main>
     </>
   )

}
