import Head from 'next/head'
//import clientPromise from '../lib/mongodb'
import { useEffect } from 'react'
import styles from '../styles/Home.module.css'
import Link from 'next/link';
import { useUser } from '@auth0/nextjs-auth0/client';




export default function Home({restaurants}){

  const { user, error, isLoading } = useUser();

  if(user){
    const userId = user.sid
  }

  function Login() {
    if(!user){
    return (
       <Link
         href={{
           pathname: '/api/auth/login'
         }}
         >
         <button>Login</button>
       </Link>
     )
    }
   }
   
   function Logout() {
     if(user){
       return (
         <Link
         href={{
           pathname: '/api/auth/logout'
         }}
         >
         <button>Logout</button>
       </Link>
       )
     }
    
    
   }
   
   function ProfileLink(){
    if(user){
     return(
         <Link
         href={{
           pathname: '/profile'
         }}
         >
         <button>Profile</button>
       </Link>
     )
    }
   }
   


  if (isLoading) return <div>Loading...</div>;
  if (error) return <div>{error.message}</div>;
 
   return (
     <>
       <Head>
         <title>Create Next App</title>
         <meta name="description" content="Generated by create next app" />
         <meta name="viewport" content="width=device-width, initial-scale=1" />
         <link rel="icon" href="/favicon.ico" />
       </Head>
       <main className={styles.main}>
        <h1>Restaurant Creator Login</h1>
    
        <Login/>
        <Logout/>
        <ProfileLink/>
       </main>
     </>
   )

}
