import Head from 'next/head'
import { useEffect, useState } from 'react'
import styles from '../styles/Login.module.css'
import Link from 'next/link';

export default function Login(){
 
    const [userEmail,setUserEmail] = useState('')
    const [userPassword,setUserPassword] = useState('')

    function loginAction(e){
        e.preventDefault()
        console.log(userEmail)
        console.log(userPassword)
    }

   return (
     <>
       <Head>
         <title>Create Next App</title>
         <meta name="description" content="Generated by create next app" />
         <meta name="viewport" content="width=device-width, initial-scale=1" />
         <link rel="icon" href="/favicon.ico" />
       </Head>
       <main className={styles.main}>
        <div className={styles.loginContainer}>
            <form onSubmit={loginAction} className={styles.formContainer}>
                <h1 className={styles.pageTitle}>Restaurant Creator Login</h1>
                <input required className={styles.formInput} placeholder='Email' type='email' onChange={e=>setUserEmail(e.target.value)} /><br/>
                <input required className={styles.formInput} placeholder='password' type='password' onChange={e=>setUserPassword(e.target.value)} />
                <button className={styles.formButton} type='submit'>Login</button>
            </form>
        </div>
       </main>
     </>
   )

}
